# Generated by Django 2.2.9 on 2021-03-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210306_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='grou',
            new_name='group',
        ),
    ]
